version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/secureDocs:/app/src/secureDocs:ro
    environment:
      - NODE_ENV=production
    command: npm start
